cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
    - wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.xz
    - tar xf node-v6.9.2-linux-x64.tar.xz
    - rm node-v6.9.2-linux-x64.tar.xz
    - cd node-v6.9.2-linux-x64/bin/
    - export PATH="$PATH:`pwd`"
    - cd ../../
    - npm install

test:
  stage: test
  script:
    - npm test
  dependencies:
    - build
