import { Profil } from './profile';

export const PROFILES: Profil[] = [
  {
    id          : '0',
    zdjecie     : '',
    nazwa       : '',
    email       : '',
    telefon     : '',
    funkcja     : 'zleceniodawca',
    ulica       : '',
    nr_bud      : '',
    kod         : '',
    miejscowosc : '',
  },
  {
    id          : '1',
    zdjecie     : '',
    nazwa       : '',
    email       : 'toudik99@gmail.com',
    telefon     : '660513959',
    funkcja     : 'zleceniodawca',
    ulica       : 'ul.Traugutta',
    nr_bud      : '71',
    kod         : '82-300',
    miejscowosc : 'Elbląg',
  },
  {
    id          : '2',
    zdjecie     : '',
    nazwa       : 'Artur Leśny',
    email       : 'toudik99@wp.pl',
    telefon     : '505433110',
    funkcja     : 'wykonawca',
    ulica       : 'ul.Obywatelska',
    nr_bud      : '7',
    kod         : '80-259',
    miejscowosc : 'Gdańsk',
  },
  {
    id          : '3',
    zdjecie     : '',
    nazwa       : '',
    email       : 'artur_lesny@wp.pl',
    telefon     : '502313100',
    funkcja     : 'zleceniodawca',
    ulica       : 'al.Grunwaldzka',
    nr_bud      : '123',
    kod         : '80-266',
    miejscowosc : 'Gdańsk',
  },
];
