export interface OgloszenieMiniatura {
  identyfikator: string,
  zdjecie: string,
  tytul: string,
  nazwa_zlecenia: string,
  rodzaj_zlecenia: string,
  lokalizacja: string,
  miejscowosc: string,
  ulica: string,
  opis: string,
  cena_max: number,
  data_dodania: string,
  czas_wykonania: string,
  czas_licytacji: string,
}
